cursor #161d1e
cursor_text_color #3c494b

foreground            #161d1e
background            #f4fbfb
selection_foreground  #ffffff
selection_background  #9ecfd6
url_color             #006972

color0   #0e1415
color1   #8c0b13
color2   #117209
color3   #7f6d11
color4   #42d1dd
color5   #095a60
color6   #006972
color7   #1a1a1a
color8   #2e2e2e
color9   #a52028
color10  #1d8c13
color11  #998521
color12  #007d88
color13  #3efbe8
color14  #57a0fb
color15  #1a1a1a
