exec-once = systemctl --user restart noctalia.service

bind = SUPER, A, exec, qs -c noctalia-shell ipc call launcher toggle
bind = SUPER, V, exec, qs -c noctalia-shell ipc call launcher clipboard
bind = SUPER, L, exec, qs -c noctalia-shell ipc call lockScreen lock
