############# Cursor ##########
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24 

############# Wayland #############
env = ELECTRON_OZONE_PLATFORM_HINT,auto

############## Themes #############
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,kde
env = XDG_MENU_PREFIX,plasma-

############## Softwares ##########
env = TERMINAL,kitty,-1

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

